# Generated by Django 3.2.6 on 2021-08-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['datetime'], name='transaction_datetim_2f916f_idx'),
        ),
    ]
